In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('final.csv')

In [3]:
df

,6,12,29,52,75,91,99,97,87,68,...,85.3,95.1,96.2,88.1,72,50,29.2,12.4,6.3,0
0,6,11,27,50,74,92,101,101,92,74,...,91,101,101,92,74,51,28,12,7,0
1,7,13,31,55,79,96,108,114,111,98,...,66,70,70,67,58,44,26,12,7,0
2,7,14,31,55,76,91,98,99,91,75,...,79,85,85,78,66,47,27,12,6,0
3,20,30,52,70,80,86,92,96,95,88,...,98,103,106,105,102,94,73,44,30,0
4,20,31,54,75,90,102,110,111,106,96,...,107,109,108,104,97,84,62,37,25,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128084,29,43,72,104,130,148,159,161,155,139,...,21,25,24,20,13,7,3,1,0,4
128085,27,36,51,62,67,72,76,79,83,85,...,121,122,121,118,107,80,43,16,6,4
128086,0,0,1,6,18,36,55,65,67,60,...,101,110,112,111,110,109,103,93,86,4
128087,12,23,50,76,93,99,102,104,108,113,...,6,9,12,12,10,7,4,2,1,4
128088,1,3,11,26,42,55,66,76,84,89,...,21,31,35,35,29,21,13,7,4,4

In [4]:
x=df.iloc[:,:-1]
x

,6,12,29,52,75,91,99,97,87,68,...,67.2,85.3,95.1,96.2,88.1,72,50,29.2,12.4,6.3
0,6,11,27,50,74,92,101,101,92,74,...,72,91,101,101,92,74,51,28,12,7
1,7,13,31,55,79,96,108,114,111,98,...,58,66,70,70,67,58,44,26,12,7
2,7,14,31,55,76,91,98,99,91,75,...,66,79,85,85,78,66,47,27,12,6
3,20,30,52,70,80,86,92,96,95,88,...,90,98,103,106,105,102,94,73,44,30
4,20,31,54,75,90,102,110,111,106,96,...,102,107,109,108,104,97,84,62,37,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128084,29,43,72,104,130,148,159,161,155,139,...,15,21,25,24,20,13,7,3,1,0
128085,27,36,51,62,67,72,76,79,83,85,...,114,121,122,121,118,107,80,43,16,6
128086,0,0,1,6,18,36,55,65,67,60,...,81,101,110,112,111,110,109,103,93,86
128087,12,23,50,76,93,99,102,104,108,113,...,3,6,9,12,12,10,7,4,2,1
128088,1,3,11,26,42,55,66,76,84,89,...,10,21,31,35,35,29,21,13,7,4

In [5]:
y=df.iloc[:,-1]
y

0         0
1         0
2         0
3         0
4         0
         ..
128084    4
128085    4
128086    4
128087    4
128088    4
Name: 0, Length: 128089, dtype: int64

In [6]:
rank = np.linalg.matrix_rank(x)

print("Rank of the matrix:", rank)

Rank of the matrix: 196

In [7]:
x=x/255
x

,6,12,29,52,75,91,99,97,87,68,...,67.2,85.3,95.1,96.2,88.1,72,50,29.2,12.4,6.3
0,0.023529,0.043137,0.105882,0.196078,0.290196,0.360784,0.396078,0.396078,0.360784,0.290196,...,0.282353,0.356863,0.396078,0.396078,0.360784,0.290196,0.200000,0.109804,0.047059,0.027451
1,0.027451,0.050980,0.121569,0.215686,0.309804,0.376471,0.423529,0.447059,0.435294,0.384314,...,0.227451,0.258824,0.274510,0.274510,0.262745,0.227451,0.172549,0.101961,0.047059,0.027451
2,0.027451,0.054902,0.121569,0.215686,0.298039,0.356863,0.384314,0.388235,0.356863,0.294118,...,0.258824,0.309804,0.333333,0.333333,0.305882,0.258824,0.184314,0.105882,0.047059,0.023529
3,0.078431,0.117647,0.203922,0.274510,0.313725,0.337255,0.360784,0.376471,0.372549,0.345098,...,0.352941,0.384314,0.403922,0.415686,0.411765,0.400000,0.368627,0.286275,0.172549,0.117647
4,0.078431,0.121569,0.211765,0.294118,0.352941,0.400000,0.431373,0.435294,0.415686,0.376471,...,0.400000,0.419608,0.427451,0.423529,0.407843,0.380392,0.329412,0.243137,0.145098,0.098039
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128084,0.113725,0.168627,0.282353,0.407843,0.509804,0.580392,0.623529,0.631373,0.607843,0.545098,...,0.058824,0.082353,0.098039,0.094118,0.078431,0.050980,0.027451,0.011765,0.003922,0.000000
128085,0.105882,0.141176,0.200000,0.243137,0.262745,0.282353,0.298039,0.309804,0.325490,0.333333,...,0.447059,0.474510,0.478431,0.474510,0.462745,0.419608,0.313725,0.168627,0.062745,0.023529
128086,0.000000,0.000000,0.003922,0.023529,0.070588,0.141176,0.215686,0.254902,0.262745,0.235294,...,0.317647,0.396078,0.431373,0.439216,0.435294,0.431373,0.427451,0.403922,0.364706,0.337255
128087,0.047059,0.090196,0.196078,0.298039,0.364706,0.388235,0.400000,0.407843,0.423529,0.443137,...,0.011765,0.023529,0.035294,0.047059,0.047059,0.039216,0.027451,0.015686,0.007843,0.003922
128088,0.003922,0.011765,0.043137,0.101961,0.164706,0.215686,0.258824,0.298039,0.329412,0.349020,...,0.039216,0.082353,0.121569,0.137255,0.137255,0.113725,0.082353,0.050980,0.027451,0.015686

In [8]:
from sklearn.model_selection import train_test_split, GridSearchCV

In [9]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [10]:
from sklearn.metrics import accuracy_score, classification_report

In [11]:
from sklearn.tree import DecisionTreeClassifier

In [12]:
dt_classifier = DecisionTreeClassifier()

In [13]:
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [2, 3, 4, 5, 6, 7, 8],
    'min_samples_split': [2, 3, 4, 5],
    'min_samples_leaf': [1, 2, 3, 4, 5]
}

In [14]:
grid_search = GridSearchCV(estimator=dt_classifier, param_grid=param_grid, cv=5, scoring='accuracy')

In [15]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 3, 4, 5, 6, 7, 8],
                         'min_samples_leaf': [1, 2, 3, 4, 5],
                         'min_samples_split': [2, 3, 4, 5]},
             scoring='accuracy')

In [16]:
print("Best parameters found by GridSearchCV:")
print(grid_search.best_params_)

Best parameters found by GridSearchCV:
{'criterion': 'gini', 'max_depth': 8, 'min_samples_leaf': 4, 'min_samples_split': 3}

In [17]:
best_dt_classifier = grid_search.best_estimator_

In [18]:
y_pred = best_dt_classifier.predict(X_test)

In [19]:
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.3961277226949801

In [20]:
from sklearn.metrics import confusion_matrix

In [21]:
cm = confusion_matrix(y_test, y_pred)

In [22]:
cm

array([[4940,   48,   13,   77,   79],
       [ 842, 1030,  252, 1786, 1274],
       [1307,  641,  233, 1776, 1326],
       [ 579,  499,  133, 2242, 1534],
       [ 469,  567,  206, 2062, 1703]], dtype=int64)

In [23]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.61      0.96      0.74      5157
           1       0.37      0.20      0.26      5184
           2       0.28      0.04      0.08      5283
           3       0.28      0.45      0.35      4987
           4       0.29      0.34      0.31      5007

    accuracy                           0.40     25618
   macro avg       0.37      0.40      0.35     25618
weighted avg       0.37      0.40      0.35     25618