In [19]:
import pandas as pd
import numpy as np

In [20]:
df=pd.read_csv('final.csv')

In [21]:
df

,0,0.1,0.2,0.3,1,3,9,19,33,47,...,40.2,24.1,12.1,5.5,1.17,0.36,0.37,0.38,0.39,0.40
0,0,0,0,0,1,3,9,19,33,47,...,39,23,12,5,1,0,0,0,0,0
1,0,0,0,0,1,5,13,26,43,60,...,36,23,12,5,1,0,0,0,0,0
2,0,0,0,0,1,5,14,27,43,59,...,36,22,11,4,1,0,0,0,0,0
3,0,1,4,14,31,49,62,69,73,76,...,92,91,87,74,50,24,7,1,0,0
4,0,1,3,12,29,48,62,68,72,78,...,87,83,76,62,41,19,6,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125750,0,0,0,0,0,0,0,0,1,2,...,60,57,50,39,28,17,8,3,1,4
125751,0,0,0,2,10,26,42,52,56,57,...,119,113,102,77,42,15,3,0,0,4
125752,60,79,107,112,99,87,80,78,80,83,...,1,1,0,0,0,0,0,0,0,4
125753,24,33,54,74,87,94,96,96,94,91,...,0,0,0,0,0,0,0,0,0,4
125754,2,2,4,11,27,47,61,71,77,86,...,70,67,65,61,54,38,18,5,1,4

In [22]:
x=df.iloc[:,:-1]
x

,0,0.1,0.2,0.3,1,3,9,19,33,47,...,55.3,40.2,24.1,12.1,5.5,1.17,0.36,0.37,0.38,0.39
0,0,0,0,0,1,3,9,19,33,47,...,54,39,23,12,5,1,0,0,0,0
1,0,0,0,0,1,5,13,26,43,60,...,47,36,23,12,5,1,0,0,0,0
2,0,0,0,0,1,5,14,27,43,59,...,49,36,22,11,4,1,0,0,0,0
3,0,1,4,14,31,49,62,69,73,76,...,92,92,91,87,74,50,24,7,1,0
4,0,1,3,12,29,48,62,68,72,78,...,91,87,83,76,62,41,19,6,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125750,0,0,0,0,0,0,0,0,1,2,...,59,60,57,50,39,28,17,8,3,1
125751,0,0,0,2,10,26,42,52,56,57,...,123,119,113,102,77,42,15,3,0,0
125752,60,79,107,112,99,87,80,78,80,83,...,1,1,1,0,0,0,0,0,0,0
125753,24,33,54,74,87,94,96,96,94,91,...,0,0,0,0,0,0,0,0,0,0
125754,2,2,4,11,27,47,61,71,77,86,...,72,70,67,65,61,54,38,18,5,1

In [23]:
y=df.iloc[:,-1]
y

0         0
1         0
2         0
3         0
4         0
         ..
125750    4
125751    4
125752    4
125753    4
125754    4
Name: 0.40, Length: 125755, dtype: int64

In [24]:
rank = np.linalg.matrix_rank(x)

print("Rank of the matrix:", rank)

Rank of the matrix: 784

In [25]:
x=x/255
x

,0,0.1,0.2,0.3,1,3,9,19,33,47,...,55.3,40.2,24.1,12.1,5.5,1.17,0.36,0.37,0.38,0.39
0,0.000000,0.000000,0.000000,0.000000,0.003922,0.011765,0.035294,0.074510,0.129412,0.184314,...,0.211765,0.152941,0.090196,0.047059,0.019608,0.003922,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.003922,0.019608,0.050980,0.101961,0.168627,0.235294,...,0.184314,0.141176,0.090196,0.047059,0.019608,0.003922,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.003922,0.019608,0.054902,0.105882,0.168627,0.231373,...,0.192157,0.141176,0.086275,0.043137,0.015686,0.003922,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.003922,0.015686,0.054902,0.121569,0.192157,0.243137,0.270588,0.286275,0.298039,...,0.360784,0.360784,0.356863,0.341176,0.290196,0.196078,0.094118,0.027451,0.003922,0.000000
4,0.000000,0.003922,0.011765,0.047059,0.113725,0.188235,0.243137,0.266667,0.282353,0.305882,...,0.356863,0.341176,0.325490,0.298039,0.243137,0.160784,0.074510,0.023529,0.003922,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125750,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.003922,0.007843,...,0.231373,0.235294,0.223529,0.196078,0.152941,0.109804,0.066667,0.031373,0.011765,0.003922
125751,0.000000,0.000000,0.000000,0.007843,0.039216,0.101961,0.164706,0.203922,0.219608,0.223529,...,0.482353,0.466667,0.443137,0.400000,0.301961,0.164706,0.058824,0.011765,0.000000,0.000000
125752,0.235294,0.309804,0.419608,0.439216,0.388235,0.341176,0.313725,0.305882,0.313725,0.325490,...,0.003922,0.003922,0.003922,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
125753,0.094118,0.129412,0.211765,0.290196,0.341176,0.368627,0.376471,0.376471,0.368627,0.356863,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
125754,0.007843,0.007843,0.015686,0.043137,0.105882,0.184314,0.239216,0.278431,0.301961,0.337255,...,0.282353,0.274510,0.262745,0.254902,0.239216,0.211765,0.149020,0.070588,0.019608,0.003922

In [26]:
from sklearn.model_selection import train_test_split, GridSearchCV

In [27]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [28]:
from sklearn.metrics import accuracy_score, classification_report

In [29]:
from sklearn.tree import DecisionTreeClassifier

In [30]:
dt_classifier = DecisionTreeClassifier()

In [31]:
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [2, 3, 4, 5, 6, 7, 8],
    'min_samples_split': [2, 3, 4, 5],
    'min_samples_leaf': [1, 2, 3, 4, 5]
}

In [32]:
grid_search = GridSearchCV(estimator=dt_classifier, param_grid=param_grid, cv=5, scoring='accuracy')

In [33]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 3, 4, 5, 6, 7, 8],
                         'min_samples_leaf': [1, 2, 3, 4, 5],
                         'min_samples_split': [2, 3, 4, 5]},
             scoring='accuracy')

In [34]:
print("Best parameters found by GridSearchCV:")
print(grid_search.best_params_)

Best parameters found by GridSearchCV:
{'criterion': 'entropy', 'max_depth': 8, 'min_samples_leaf': 1, 'min_samples_split': 5}

In [35]:
best_dt_classifier = grid_search.best_estimator_

In [36]:
y_pred = best_dt_classifier.predict(X_test)

In [37]:
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.43564868196095585

In [38]:
from sklearn.metrics import confusion_matrix

In [39]:
cm = confusion_matrix(y_test, y_pred)

In [40]:
cm

array([[5099,   14,    7,   18,   17],
       [ 586, 1494,  390, 2570,  210],
       [1167,  757,  361, 2694,  200],
       [ 369,  482,  216, 3672,  295],
       [ 265,  579,  257, 3101,  331]], dtype=int64)

In [41]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.68      0.99      0.81      5155
           1       0.45      0.28      0.35      5250
           2       0.29      0.07      0.11      5179
           3       0.30      0.73      0.43      5034
           4       0.31      0.07      0.12      4533

    accuracy                           0.44     25151
   macro avg       0.41      0.43      0.36     25151
weighted avg       0.41      0.44      0.37     25151

In [42]:
from sklearn.ensemble import RandomForestClassifier

In [43]:
rf_classifier = RandomForestClassifier()

In [44]:
param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [None, 5, 10, 15],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [45]:
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, cv=5, scoring='accuracy')

In [46]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [None, 5, 10, 15],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [50, 100, 150]},
             scoring='accuracy')

In [47]:
print("Best parameters found by GridSearchCV:")
print(grid_search.best_params_)

Best parameters found by GridSearchCV:
{'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 150}

In [48]:
best_rf_classifier = grid_search.best_estimator_

In [49]:
y_pred = best_rf_classifier.predict(X_test)

In [50]:
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.5169575762395133

In [51]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[5078,   11,   45,    9,   12],
       [ 494, 2526,  708,  967,  555],
       [1051, 1118,  984, 1275,  751],
       [ 227,  664,  524, 2691,  928],
       [ 149,  707,  517, 1437, 1723]], dtype=int64)

In [52]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.73      0.99      0.84      5155
           1       0.50      0.48      0.49      5250
           2       0.35      0.19      0.25      5179
           3       0.42      0.53      0.47      5034
           4       0.43      0.38      0.41      4533

    accuracy                           0.52     25151
   macro avg       0.49      0.51      0.49     25151
weighted avg       0.49      0.52      0.49     25151